sudo: required

language: python
python:
  - "2.6"
  - "2.7"

services:
  - docker

install: true

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cat /etc/default/docker

script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
