sudo: required

services:
  - docker

install: true

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - sudo cat /etc/default/docker

script:
  - docker version
  - ./build.sh $TRAVIS_BUILD_NUMBER

notifications:
  email: true
