sudo: required

services:
  - docker

laguage: python

python:
  - "2.6"
  - "2.7"

install: true

before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - sudo cat /etc/default/docker

script:
  - docker version
  - ./build.sh $TRAVIS_BUILD_NUMBER

notifications:
  email: true

after_success:
  - echo "All done!"
