apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/saidsef/aws-elastic-beanstalk-docker-sample-application:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/saidsef/aws-elastic-beanstalk-docker-sample-application:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: aws-elastic-beanstalk-docker-sample-application
        chartPath: charts/aws-elastic-beanstalk-docker-sample-application
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/saidsef/aws-elastic-beanstalk-docker-sample-application"
          image.tag: "{{.DIGEST_HEX}}"
        
